config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  get 'home/index'
  root 'home#index'

  resources :profile, only: [:index]
  resources :ads, only: [:create, :new, :show]
  resources :ad_detail, only: [:show]
  get 'search', to: 'search#ads'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :home do
  	collection do
  		get 'search'
  	end
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :member
  #Validates
  validates_presence_of :title, :description, :price, :image

  #gem money-rails
  monetize :price_cents
  #carrierwave mount
  mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :ads

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ad_detail_controller.rb
class AdDetailController < ApplicationController
  layout 'site'
  def show
    @ad = Ad.find(params[:id])
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member

    if @ad.save
      redirect_to profile_index_path, notice: "Anúncio cadastrado com sucesso!"
    else
      render :new
    end
end

  private

  def set_ad
    @ad = Ad.find(params[:id])    
  end

  def params_ad
    params.require(:ad).permit(:id, :title, :price, :description, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "site"
  def index
    @ads = Ad.limit(6).order(created_at: :desc)
    @carousel = Ad.limit(3).order("RANDOM()")
  end

  def search
    @ads = Ad.where("title LIKE ?", "%#{params[:q]}%")
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  layout "profile"
  def index
    @ads = Ad.where(member_id: current_member.id)
  end
end

app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/ad_detail/show.html.erb
<div class="container">
	<div class="col-md-9">
		<div class="thumbnail">
			<%= image_tag @ad.image_url, class: "img-responsive" %>
			<div class="caption-full">
				<h4 class="pull-right"><%= humanized_money_with_symbol @ad.price %></h4>
				<h4><%= @ad.title  %></h4>
				<%= @ad.description  %>
			</div>
			<div class="ratings">
				<p class="pull-right">Ad criado por <%= @ad.member.email %></p>
				<p>
					<span class="glyphicon glyphicon-star"></span>
					<span class="glyphicon glyphicon-star"></span>
					<span class="glyphicon glyphicon-star"></span>
					<span class="glyphicon glyphicon-star"></span>
					<span class="glyphicon glyphicon-star-empty"></span>
					4.0 stars
				</p>
			</div>
		</div>
	</div>
</div>

app/views/ads/new.html.erb
<%= stylesheet_link_tag 'ads', media: 'all', 'data-turbolinks-track': 'reload' %>
<% if @ad.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<!-- Container -->
<div class="container">
  <%= form_for @ad, html: { multipart: true, class: "well form-horizontal" } do |f| %>
    <fieldset>
      <legend>Novo Anúncio</legend>
        <!-- campo Titulo-->
        <div class="form-group">
          <%= f.label :title, class: "col-md-4 control-label" %>
          <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
              <%= f.text_field :title, class: "form-control", placeholder: "Título" %>
            </div>
          </div>
        </div>
        <!-- campo price currency -->
        <div class="form-group">
            <%= f.label :price, class: "col-md-4 control-label" %>
            <div class="col-md-4 inputGroupContainer">
              <div class="input-group">
                <div class="input-group-addon"><%= @ad.price.currency.symbol %></div>
                <%= f.text_field :price, class: "form-control", placeholder: "Título" %>
                  </div>
            </div>
          </div>
        <!-- campo image -->
        <div class="form-group">
          <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
              <%= f.label :image %>
              <%= f.file_field :image, class: "btn" %>
            </div>
          </div>
        </div>
        <!-- campo description -->
        <div class="form-group">
            <%= f.label :description, class: "col-md-4 control-label" %>
            <div class="col-md-4 inputGroupContainer">
              <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                <%= f.text_area :description, class: "form-control", placeholder: "Descrição" %>

              </div>
            </div>
          </div>
        <!-- Button -->
        <div class="form-group">
          <div class="col-md-4">
            <%= submit_tag "Enviar", class: "btn btn-warning" %>
            </div>
        </div>

      </fieldset>
    <% end %>
  </div>
</div>
<!-- /.container -->

app/views/home/index.html.erb
<!-- Page Content -->
<div class="container">
	<%= form_tag search_home_index_path, method: :get do %>
		<div class="row">
			<div class="well well-sm">
				<div class="row">
					<div class="col-lg-3"></div>
					<div class="col-lg-6">
						<div class="input-group">
              <%= text_field_tag(:q, params[:q] , { class:"form-control", placeholder: "Pesquisar..." }) %>
              <span class="input-group-btn">
                <%= submit_tag("Pesquisar", class:"btn btn-default") %>
              </span>
            </div><!-- /input-group -->
        	</div><!-- /.col-lg-6 -->
          <div class="col-lg-3"></div>
     	  </div><!-- /.row -->
   	  </div>
 		</div>
	<% end %>
	<div class="row">
		<div class="col-md-10">
			<div class="row carousel-holder">
				<div class="col-md-12">
					<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
							<li data-target="#carousel-example-generic" data-slide-to="1"></li>
							<li data-target="#carousel-example-generic" data-slide-to="2"></li>
						</ol>
						<div class="carousel-inner">
							<% @carousel.each do |ad| %>
								<div class="item <%= @carousel.first.id == ad.id ? "active": "" %>">
									<%= image_tag ad.image_url, class: "slide-image" %>
								</div>
							<%end %>
						</div>
						<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left"></span>
						</a>
						<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right"></span>
						</a>
					</div>
				</div>
			</div>
			<div class="row">
			<%= render partial: 'shared/ads' %>
			</div>
		</div>
	</div>
</div>

app/views/home/search.html.erb
<%= render partial: 'shared/ads' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>OlxHomework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>OlxHomework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/shared/navigation" %>
    <%= yield %>
    <%= render partial: "layouts/shared/footer" %>
  </body>

</html>

app/views/layouts/shared/_footer.html.erb
<!-- /.container -->

<div class="container">

    <hr>
    
    <!-- Footer -->
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; Olx Homework <%= Date.today.year %></p>
        </div>
      </div>
    </footer>
    
    </div>
    <!-- /.container -->

app/views/layouts/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  "Olx Homework", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right ">
        <div class="dropdown">
          <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">
            <% if member_signed_in? %>
              <%= current_member.email %>
            <% else %>
              Menu
            <% end %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% unless member_signed_in? %>
              <li><%= link_to "Login", new_member_session_path %></li>
              <li><%= link_to "Registrar", new_member_registration_path %></li>
            <% else %>
              <li><%= link_to "Meus Anúncios", profile_index_path %></li>
              <li><%= link_to "Cadastrar Anúncios", new_ad_path %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_member_session_path, method: :delete %> </li>
          </ul>
        </div> 
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>OlxHomework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/shared/navigation" %>
    <%= yield %>
    <%= render partial: "layouts/shared/footer" %>
  </body>

</html>

app/views/shared/_ads.html.erb
<% @ads.each do |ad| %>
<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <%= image_tag ad.image_url %>
    <div class="caption">
      <h4 class="pull-right"><%= humanized_money_with_symbol ad.price %></h4>
      <h4><%= link_to  truncate(ad.title, length: 20), ad_detail_path(ad) %></h4>
      <p><%= truncate(ad.description, length: 100) %></p>
    </div>
    <div class="ratings">
      <p>Criado por <%= ad.member.email %></p>
    </div>
  </div>
</div>
<% end %>